input {
  file {
    path => "/usr/share/logstash/pipeline/logs/LEAtTrace_siem.log"
    start_position => "beginning"
    codec => "json"
    type => "siem"
  }
  
  # Standard syslog ingest port
  syslog {
    port => 5044
    codec => "cef"
    type => "cef"
  }
}

filter {
  if [type] == "siem" {
    mutate {
      add_field => { "environment" => "production" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "LEAtTrace-siem-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
